version: "3.9"

services:
  db:
    image: postgres:13
    ports:
      - 5433:5432
    env_file: ./.env
    volumes:
      - data:/var/lib/postgresql/data/
    networks:
      - shared-network
    restart: always

networks:
  shared-network:

volumes:
  data:
